config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  resources :images
  resources :profiles
  devise_for :users 
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :verify_profile!

  protected
  def verify_profile!
    if user_signed_in?
      return if current_user.profile
      redirect_to new_profile_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show destroy ]

  def index
    @images = Image.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |f|
      if @image.save
        f.html { redirect_to @image, notice: "Image was uploaded successfully" }
        f.json { render :show, status: :created, location: @image }
      else
        f.html { render :new, status: :unprocessable_entity }
        f.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |f|
      f.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      f.json { head :no_content }
    end
  end

  private
  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:title, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  skip_before_action :verify_profile!

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = current_user.profile
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :birthday, :background_color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Photos Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Images", images_path, class: "nav-link active"  %>
        </li>
      </ul>
    </div>
    <ul class="nav justify-content-end">
      <% if user_signed_in? %>
        <div class="nav-item">
          <%= link_to 'Profile', profile_path(current_user) , class: "nav-link active" %>
        </div>
        <div class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link active" %>
        </div>
      <% else %>
        <div style="padding:5px;">
          <%= link_to 'Log In', user_session_path, class: "nav-link active"  %>
        </div>
        <div style="padding:5px;">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link active"  %>
        </div>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<h1 class="centered">Welcome Home!</h1>

app/views/images/index.html.erb
<div class="centered">
  <h1>Images</h1>
  <%= link_to 'Home', root_path %>
  <br/>
  <%= link_to 'Add Image', new_image_path %>
</div>

<% @images.each do |i| %>
  <div class="card container">
    <div class="centered">
      <strong><%= i.title %></strong>
    </div>

    <div class="center-img">
      <%= link_to image_path(i) do %>
        <%= image_tag i.image, class: "center_img" if i.image.attached? %>  
      <% end %>
    </div>
  </div>
  <br/>
<% end %>

app/views/images/new.html.erb
<h1>Images#new</h1>
<p>Find me in app/views/images/create.html.erb</p>


<%= form_with(model: @image) do |form| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% @image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/show.html.erb
<div class="centered">
  <%= link_to 'Image Home', image_path %>
</div>
<br/>
<div class="card container">
  <div class="centered">
    <strong><%= @image.title %></strong>
    <br/>
    <%= image_tag @image.image, class: "center_img"%>
    <%= link_to 'Delete', image_path(@image), method: :delete %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:<%= current_user.profile.background_color.split(" ").join if user_signed_in? && current_user.profile %>">
    <%= render 'home/nav' %>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: profile) do |form| %>
        <% if profile.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

            <ul>
              <% profile.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group row">
          <%= form.label :name, class: "col-5 col-form-label text-dark" %>
          <div class="col-6">
            <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter your name" %>
          </div>
        </div>

        <br/>

        <div class="form-group row">
          <%= form.label :birthday, class: "col-5 col-form-label text-dark" %>
          <div class="col-6">
            <%= form.date_select :birthday, start_year: 1900, end_year: Date.today.year, class: "form-control shadow rounded" %>
          </div>
        </div>

        <br/>

        <div class="form-group row">
          <%= form.label :background_color, class: "col-5 col-form-label text-dark" %>
          <div class="col-6">
            <%= form.select :background_color, ['White', 'Light Gray', 'Light Blue', 'Light Green', 'Aqua', 'Coral'], class: "form-control shadow rounded", selected: current_user.profile.nil? ? 'White' : current_user.profile.background_color %>
          </div>
        </div>

        <br/>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="card container">
  <h1>Editing Profile</h1>

  <%= render 'form', profile: @profile %>

  <div>
    <%= link_to 'Show', @profile, class: "btn btn-dark" %>
    <%= link_to 'Back', profiles_path, class: "btn btn-dark" %>
  </div>
</div> 

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Birthday</th>
      <th>Background color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user_id %></td>
        <td><%= profile.name %></td>
        <td><%= profile.birthday %></td>
        <td><%= profile.background_color %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% unless current_user.profile %>
  <%= link_to 'New Profile', new_profile_path %>
<% end %>

<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

app/views/profiles/new.html.erb
<div class="text-center mt-4">
  <h1>New Profile</h1>

  <%= render 'form', profile: @profile %>

  <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="card">
    <div class="card-header">
      <strong>Name:</strong>
      <%= @profile.name %>
    </div>
    <div class="card-body">
      <p>
        <strong>Email:</strong>
        <%= current_user.email %>
      </p>

      <p>
        <strong>Birthday:</strong>
        <%= @profile.birthday %>
      </p>

      <p>
        <strong>Background color:</strong>
        <%= @profile.background_color %>
      </p>

      <p>
        <strong>User ID:</strong>
        <%= @profile.user_id %>
      </p>

      <div>
        <%= link_to 'Edit', edit_profile_path(@profile), class: "btn btn-dark" %>
      </div>
    </div>
  </div>
</div>